project_name = "learned-acolyte-221721"
path_to_context = "/Users/sergii.marchenko/work/keys/gcp/Iegor-072a850167f3.json"
//project_name = "devproworkshop"
//path_to_context = "/root/work/keys/gcp/credentials.json"
//path_to_context = "credentials.json"
